service: aws-experiments

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'eu-west-1'}
  timeout: 300
  environment:
    SOME_BUCKET_NAME: ${self:custom.someBucketName}
    SOME_TABLE_NAME: ${self:custom.someTableName}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

custom:
  someBucketName: ${self:service}-${self:provider.region}-some-bucket
  someTableName: ${self:service}-some-table

functions:
  test:
    handler: test.handler
  coldStartTest:
    handler: coldStartTest.handler

resources:
  Resources:
    someBucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: ${self:custom.someBucketName}
    someTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.someTableName}
        AttributeDefinitions:
          - AttributeName: someKey
            AttributeType: S
        KeySchema:
          - AttributeName: someKey
            KeyType: HASH
        #SSESpecification:
        #  SSEEnabled: true
        #StreamSpecification:
        #  StreamViewType: NEW_AND_OLD_IMAGES
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
