service: lambda-hello

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  hello:
    handler: hello.handler
    events:
      - http:
          path: /hello
          method: GET
